// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace WebApplication4.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class firstClassAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstClassAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201501111309594_firstClassAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
