// <auto-generated />
namespace WebApplication4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class questions5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(questions5));
        
        string IMigrationMetadata.Id
        {
            get { return "201501171618055_questions5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
